# Generated by Django 4.2.2 on 2023-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE quiz_question ALTER COLUMN personality_type DROP NOT NULL",
            "ALTER TABLE quiz_question ALTER COLUMN personality_type SET NOT NULL",
        ),
        migrations.RemoveField(
            model_name='question',
            name='personality_type',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
